name: Deploy static site to Azure Web App - CaliSistemas

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C3C25E9C0221479D8D7A353861557420 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FB2C5A69F25242659E123F971FDA2641 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3453C38B520949268908FCFA8ED58DD4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CaliSistemas'
          slot-name: 'Production'
          package: 'public_html'
